### ISSUE TITLE
请教项目完成情况

### ISSUE THREAD

**Issue by wangzhankun** [TRCYX/riscv-user-level-interrupt#1]
同学，你好，我最近也在研究RISC v的用户态中断，请问你现在项目进展情况怎么样呀？

**Comment by TRCYX** [comment]
你好！我是作为课程项目参加这个用户态中断的设计的。如你所见，我在该学期结束之后就没有继续参与，其实我个人的完成情况也不如预期，到设计出一个能用的用户态软件中断控制器方案然后 QEMU 实现就停了。后续似乎有同学在 FPGA 上实现。我确实没有仔细关注整个大项目的进展。

我看到你在 https://github.com/Gallium70/rv-n-ext-impl/issues/2 开的 issue 了，如果我没有理解错，Gallium70 和 duskmoon314 两位是一直在做这个的。如果不太急的话可以等他们回应。

**Comment by wangzhankun** [comment]
好的，谢谢同学。

**Comment by wangzhankun** [comment]
同学，请问你知道使用到的rCore的base commit吗？我想对比一下现在的用户态中断使用的rCore和原始rCore的区别，以方便快速定位为实现用户态中断在OS中添加的代码。

**Comment by TRCYX** [comment]
不太清楚。这个基于的是教学版 rCore（应该就是 rCore Tutorial）当年的版本，是操作系统课给同学们填空用的，不知道后来有没有翻新过，和 https://github.com/rcore-os/rCore-Tutorial-v3 等有多少差别。看了一下他们两个好像直接把代码一起初始 commit 了，大概是因为是从清华 git 的作业上弄下来的，历史和 github 上的版本不见得完全一样。细节还是问他们两个比较好，毕竟最初这是他们的比赛项目。如果需要微信号之类的可以邮件联系我。

**Comment by wangzhankun** [comment]
同学，这个是我的微信号： `communism1949101`，谢谢你。
